description: |-
  While consistent hashing is largely known and adopted in the NoSQL
  database clusters to solve data distribution and data access
  reliability, it is less known and used by the typical developers.

  This talk will introduce you to consistent hashing and the problems
  it solves while going through a practical use case in a python application.

  We will start from its standalone design and scale it out to an
  optimized clustered version thanks to consistent hashing.

duration: 2610
recorded: '2017-07-11'
speakers:
- Alexys Jacob
thumbnail_url: https://i.ytimg.com/vi/erINlrgygEk/hqdefault.jpg
title: Leveraging consistent hashing in your python applications
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=erINlrgygEk

