description: |-
  Creating full-stack applications with Python, NodeJS and React can seem
  daunting at first. Having made many variations of these,
  I will show you the ropes, so you too can discover that it is in fact
  easy to get going.

  In this talk you will learn to create a full-stack web application in
  Python, with a Nodejs and React front-end.
  I will provide you with an easy-to- follow walkthrough of the process,
  and you’ll exit this talk feeling confident that you can now create
  your own full-stack web application.

duration: 1909
recorded: '2017-07-10'
speakers:
- Angela Branaes
thumbnail_url: https://i.ytimg.com/vi/nfi0hX-F8Zo/hqdefault.jpg
title: Building a full-stack web application with Python, NPM, Webpack and React
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=nfi0hX-F8Zo

