description: |-
  Network automation and orchestration is the latest phase in the evolution
  of IP and optical networks.
  Over the last few years, network engineers have created a variety of
  libraries and softwares to help them with the management, configuration and automation of huge networks made of hundreds of thousands of network devices (e.g. routers, switches, antenna...).

  In this talk, I will introduce NetDim, a vendor-neutral software
  for network modeling and automation based on the standard Python
  library for GUI programming: tkinter.

  I will start the presentation with an introduction to network visualization,
  and show how tkinter can be used to implement graph drawing algorithms,
  as well as a full-on Geographic Information System (GIS),
  allowing one to place network devices on a world map at their GPS coordinates.

  I will then discuss the whys and wherefores of network automation,
  and show how to automatically generate and push scripts to a network
  device via SSH or Telnet.

  More details about NetDim on github https://github.com/mintoo/NetDim and
  on this website http://netdim.fr

duration: 2107
recorded: '2017-07-13'
speakers:
- Antoine Fourmy
thumbnail_url: https://i.ytimg.com/vi/HUQTVbyGdHs/hqdefault.jpg
title: Network visualization and automation
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=HUQTVbyGdHs

