description: |-
  There are as many different ways to package an application as there
  are programming or scripting languages. No one tool or library is in
  itself better than another; however when security comes into the
  picture, there is definitely a pattern between ease of installation
  and how secure the delivered application is. As more work is put into
  packaging the application, more measures can be taken in order to
  ensure its integrity and prevent security issues.

  This talk will cover:

  - The roles involved in the lifecycle of an application, from the
    start of the development process until it reaches the end user and it
    is actually used.
  - The inherent problems in this subject, regarding installation and
    security, as well as how they are related.
  - The different ways of packaging an application in order to deliver
    it to an end user, focused on a Python perspective.

  After the talk, attendees will have a better grasp on which is the
  best way for them to package and deliver their application according
  to their environment and target audience. They will also learn about
  the upgrade path to switch from one delivery method to another,
  should they need or want to.

  For this talk, it is desired that attendees have some general systems
  knowledge. Even though the talk will be focused on Python
  applications, some knowledge of information security is desired.

duration: 1399
recorded: '2017-07-11'
speakers:
- Juan Manuel Santos
thumbnail_url: https://i.ytimg.com/vi/ZFCAE8rxP7E/hqdefault.jpg
title: You need more security in your application packaging
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=ZFCAE8rxP7E

