description: |-
  Serverless computing: it is the practice of building and running
  services and applications without having to worry about provisioning
  and managing servers. Serverless computing has been a popular topic
  the past couple years, and with respect to Python, there have been
  various different frameworks and tools released for developing and
  managing your Python serverless applications. This talk will focus on
  developing and managing your serverless applications with chalice
  (https://github.com/awslabs/chalice), a python serverless
  microframework for AWS. Discussion points for this talk will include,
  but not be limited to:

  - Overview of serverless applications
  - Best practices in writing a serverless application
  - Basic usage and core features of chalice
  - Writing complete, production-level applications using chalice
  - Managing and maintaining serverless applications using chalice tooling

  By the end of the talk, audience members should have a better
  understanding of serverless computing and how to use chalice to
  develop and maintain serverless applications.

duration: 2705
recorded: '2017-07-11'
speakers:
- Kyle Knapp
thumbnail_url: https://i.ytimg.com/vi/33-0xdxp9-I/hqdefault.jpg
title: Serverless Applications with Chalice
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=33-0xdxp9-I

