description: |-
  Goal

  After this session, audiences will get

  - Basic knowledge of OpenAPI (Swagger)
  - Ecosystem of OpenAPI(Swagger) and tools related to Python and knowledge to make use of them in their own projects

  Audience

  (1) This talk is for:

  - Developers who are creating or using API services such as web applications, mobile applications and all other kinds of applications

  (2) Audience will be expected to have (prerequisite):

  - Basic knowledge of development with API (REST and others)
  - Basic knowledge of Python

  Outline

  Introduction (3min)


  - Agenda of this talk
  - Myself introduction


  OpenAPI(Swagger) introduction and basics (8min)

  What is OpenAPI and what is the relation with Swagger? (5min)

  Comparison with other frameworks for APIs (3min)

  - api blueprint, json schema and ..


  OpenAPI ecosystem and tools (8min)

  OpenAPI(Swagger) core tools (4min)

  Swagger editor, Swagger codegen and Swagger UI

  OpenAPI tools related to Python (4min)

  - Some tools for python api development with OpenAPI


  Actual case study with OpenAPI and Python (8min)

  - Introduce our projects with OpenAPI, Python and other program (like
    Angular, Typescript and so on) and explain how swagger is well
    working in our company


  Recap and Conclusion (2min)
duration: 1575
recorded: '2017-07-11'
speakers:
- Takuro Wada
thumbnail_url: https://i.ytimg.com/vi/OYTtlEUSDBE/hqdefault.jpg
title: OpenAPI development with Python
videos:
- type: youtube
  url: https://www.youtube.com/watch?v=OYTtlEUSDBE

